Section "Device"
    Identifier "XboxVideo"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/card0"
    Option "AccelMethod" "none"
    Option "SWcursor" "true"
    Option "PageFlip" "false"
EndSection
Section "Screen"
    Identifier "XboxScreen"
    Device "XboxVideo"
    DefaultDepth 24
EndSection
